### ISSUE TITLE
Upgrade pnpm

### ISSUE THREAD

**Issue by kronosapiens** [JoinColony/colonyNetwork#1302]
Our current `pnpm` version doesn't support pre/post scripts. The newer version does.

**Comment by area** [comment]
Can you explain why this is necessary, and why [configuring them to run](https://pnpm.io/cli/run#enable-pre-post-scripts) isn't sufficient? Without good reason, we are sticking with `pnpm` version 8 to [match with ColonyJS](https://github.com/JoinColony/colonyNetwork/pull/1249#issuecomment-2090539999) until I hear otherwise from Chris.
