### ISSUE TITLE
Agree ownership of upgradable contracts we are responsible for

### ISSUE THREAD

**Issue by filiplazovic** [JoinColony/colonyNetwork#260]
We have to agree the ownership of the following contracts and their resolvers:

MetaColony
ColonyNetwork
TokenLocking
(ReputationMiningCycle)

**Comment by kronosapiens** [comment]
Can someone clarify what this issue refers to? That we are responsible for maintaining and releasing upgrades to these contracts? Or that the contracts mentioned above are permissioned such that they can be modified only by the meta colony?

**Comment by elenadimitrova** [comment]
Currently for testing, these contracts are owned by the coinbase test account, i.e. `accounts[0]` in truffle tests. In reality, these will likely be owned by a multisig controlled by us which will either be the same one that owns the CLNY token or different. 
@area can correct me if I'm missing something

**Comment by elenadimitrova** [comment]
Initially the Colony MultiSig (`0x710e4c6ede91ef8de2f65d221316cf7448d3cf1c`) will be the (`DSAuth`) owner of the `ColonyNetwork` and `TokenLocking` contracts. After voting and disputes functionality is deployed, ownership will cede to the `MetaColony` as defined in the white paper, particularly section `3.3 Handing off decision-making power to the Meta Colony`. 

As for the `MetaColony`, since colonies' owner is set of `0x0` the Founder role there will likely be set to the same multisig as above, additionally MetaColony Admins will be added to allow for an easier task lifecycle management (without having to go through a multisig approval for every step of the task lifecycle).

**Comment by elenadimitrova** [comment]
Confirmed with @area and @jakzilla
