### ISSUE TITLE
Token minting event doesn't follow the ERC20 suggestions 

### ISSUE THREAD

**Issue by jakub-wojciechowski** [JoinColony/colonyNetwork#421]
## Summary
Token contract doesn't follow the specification described in the ERC20 token standard.

## Steps to Reproduce (for bugs)
Execute the `mint` function from the Token.sol contract

## Expected Behavior
According to the ERC20 specification (https://github.com/ethereum/EIPs/blob/master/EIPS/eip-20.md#transfer-1):

_A token contract which creates new tokens SHOULD trigger a Transfer event with the _from address set to 0x0 when tokens are created._

## Current Behaviour
A custom mint event is emitted: 

`emit Mint(msg.sender, wad);`

## Possible Solution
Emit an event which follows the specification:

`emit Transfer(0x0, msg.sender, wad);`

## Context
Having a basic token contract which is not compatible with standards will make it really hard to follow the flow of tokens on the popular block explorers, such as etherscan.

**Comment by gichiba** [comment]
Thanks for the submission @jakub-wojciechowski -- it's been accepted and the team will be discussing the severity over the next few days.

**Comment by jakub-wojciechowski** [comment]
Thx @gichiba, it's an awesome project and I'm really impressed by the quality of your code. I've just scratched the surface but I'm looking forward to dig deeper if the time allows.

**Comment by elenadimitrova** [comment]
Thanks for the submission @jakub-wojciechowski !

This is part intentional as we reuse the [dappsys library token](https://github.com/dapphub/dappsys-monolithic/blob/002389d43cf54e8f0b919fee1fc364b20ebdf626/token.sol#L80), that doesn't match up a handful of ERC20 SHOULD points, including this `Transfer` convention and `bytes32` metadata. We previously decided to adjust the `bytes32` metadata to `string` as per the standard and have decided to do the same for the `Transfer` event you point out here while keeping the dappsys token `Mint` event.

We've decided to reward you with a "Note" bounty as even though this can't be exploited it is worth polishing off. Note that rewards are paid out to your GitHub handle via [GitCoin](https://gitcoin.co/issue/JoinColony/colonyNetwork/403/1659) please make sure you select "Start work" on it if you haven't already.
