### ISSUE TITLE
Malfunctioning taskExists modifier, an edge case of the task Id == 0

### ISSUE THREAD

**Issue by jakub-wojciechowski** [JoinColony/colonyNetwork#422]
## Summary
The `taskExists` modifier doesn't include an edge case of a `0` id for task and will answer that such a task exists even if no tasks have been added at all. 

## Steps to Reproduce (for bugs)
Call any method which uses the `taskExists` modifier with the `0` as the id parameter. 

## Expected Behavior
It should answer false for the `0` task id. 

## Current Behaviour
Returns true.

## Possible Solution
Handle the `0` as a special case.

## Context
It could break the invariant checks performed in the ColonyTask.sol contract.

## Environment

* Operating System:
* Ethereum client:
* solc version:

**Comment by elenadimitrova** [comment]
Thanks (again!) @jakub-wojciechowski !

You're right about `taskExists` so we've considered this as a valid submission, however as it currently stands no updates can be made to task with Id `0` even though this modifier will indeed return `true`. This is due to the task update mechanism we have enforced of going either via `executeTaskChange` or `executeTaskRoleAssignment` functions, which both require a specific set of signatures of either task manager, worker or evaluator or a combination of two of them. Because no task manager can be assigned, no further changes can be made. This is not to say that there wouldn't be a function introduced sometime in the future that reused `taskExists` thus introducing a vulnerability and so for this we've still decided to reward you with a "Note" bounty.
Reward will be paid out to your GitHub handle via [GitCoin](https://gitcoin.co/issue/JoinColony/colonyNetwork/403/1659)

**Comment by collinvine** [comment]
@jakub-wojciechowski Can you go back to the [GitCoin issue](https://gitcoin.co/issue/JoinColony/colonyNetwork/403/1659) and `Submit` your work so that I can pay you out? Once you do that, I'll send your payment in DAI.
