### ISSUE TITLE
Unable to `finalizeTask` if `skillId` is never set

### ISSUE THREAD

**Issue by ryanchristo** [JoinColony/colonyNetwork#473]
## Summary

At the moment, it’s possible to create a task without setting the `skillId`, then assign a worker, submit the work, and rate and reveal the task roles. Then, when attempting to finalize the task, a revert error is thrown (`colony-invalid-skill-id`) and it is no longer possible to change the `skillId`, preventing any further actions associated with the task.

## Steps to Reproduce

1. `makeTask` without setting the `skillId` (defaults to `0`)
2. `setTaskWorkerRole`
3. `submitTaskDeliverable`
4. `submitTaskWorkRating` for both manager and worker
5. `revealTaskWorkRating` for both manager and worker
6. `finalizeTask`

## Expected Behavior

Either the `skillId` should be checked before the work can be submitted (submitting the work will prevent any further modifications to the task) or a `skillId` of `0` should be valid.

## Current Behaviour

```
  Runtime Error: revert
  Revert reason: colony-invalid-skill-id
```

## Possible Solution

1. Allow `skillId >= 0` in `modifier skillExists`
2. If the `skillId` should not be `0`, verify the `skillId` when calling `submitTaskDeliverable`

**Comment by kronosapiens** [comment]
Noting that in the tests, GLOBAL_SKILL has id 1. I'm not sure if there is a skill with id 0...

One option is to have the skill default to 1 instead of 0, if we're comfortable with a default at all. Alternatively, we can say that tasks _must_ set a skill, in which case raising an exception during submission is probably the best way to to (alternatively, when the worker is assigned).

**Comment by elenadimitrova** [comment]
There is indeed no skill with ID 0, all our number sequence IDs are 1-based, including colony ids, task ids, domain ids and skill ids.
