### ISSUE TITLE
Cancelling Funding Proposals

### ISSUE THREAD

**Issue by elenadimitrova** [JoinColony/colonyNetwork#78]
### 8.2.16 Cancelling Funding Proposals
The creator of a funding proposal may set its `CurrentState` to `cancelled`. This is analogous to the creator of a task being able to cancel the task if it has not yet been assigned a worker (see Section 4.1). Beyond this it must be possible for a colony to cancel a funding proposal without the creator’s involvement. This is done through the objection mechanism described in Section 9.
When a task is cancelled, funding proposals that have that task’s pot as their target (`To`) also enter the `Cancelled` state when they are next pinged, and no funds are reallocated. However, the funds that had already been transferred are not automatically returned; it will require a PFP to return the funds ‘upstream’*.
*It is conceivable that such return-funds-from-cancelled-tasks PFPs have lower hurdles of activation.

**Comment by kronosapiens** [comment]
No longer relevant in the current WP -- the creator can cancel, but otherwise reputation holders should withdraw support if they believe it is a bad proposal.

It is not currently possible to cancel a proposal if the related task is cancelled (i.e. from within a call to `pingProposal`), due to the data structures used.
